### ISSUE TITLE
readme says I can npm install this, it lies

### ISSUE THREAD

**Issue by nrstott** [Gozala/teleport#17]
npm install teleport

npm ERR! 404 Looks like 'teleport' is not in the npm registry.

**Comment by Gozala** [comment]
Hey I'm glad you got interested, but sorry it's not on npm yet. I have a dependency on Kris Kowal's "q" and I'm waiting before he will merge my changes to go live.

I'll make sure to ping you once it's there.

**Comment by nrstott** [comment]
cool thanks
